#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_JobSearch.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JobStar")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoanhNghiep(DoanhNghiep instance);
    partial void UpdateDoanhNghiep(DoanhNghiep instance);
    partial void DeleteDoanhNghiep(DoanhNghiep instance);
    partial void InsertUV_TTD(UV_TTD instance);
    partial void UpdateUV_TTD(UV_TTD instance);
    partial void DeleteUV_TTD(UV_TTD instance);
    partial void InsertFileND(FileND instance);
    partial void UpdateFileND(FileND instance);
    partial void DeleteFileND(FileND instance);
    partial void InsertGopY(GopY instance);
    partial void UpdateGopY(GopY instance);
    partial void DeleteGopY(GopY instance);
    partial void InsertHoSoXinViec(HoSoXinViec instance);
    partial void UpdateHoSoXinViec(HoSoXinViec instance);
    partial void DeleteHoSoXinViec(HoSoXinViec instance);
    partial void InsertNhaTuyenDung(NhaTuyenDung instance);
    partial void UpdateNhaTuyenDung(NhaTuyenDung instance);
    partial void DeleteNhaTuyenDung(NhaTuyenDung instance);
    partial void InsertPhiTinTuyenDung(PhiTinTuyenDung instance);
    partial void UpdatePhiTinTuyenDung(PhiTinTuyenDung instance);
    partial void DeletePhiTinTuyenDung(PhiTinTuyenDung instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTinTuyenDung(TinTuyenDung instance);
    partial void UpdateTinTuyenDung(TinTuyenDung instance);
    partial void DeleteTinTuyenDung(TinTuyenDung instance);
    partial void InsertUngVien(UngVien instance);
    partial void UpdateUngVien(UngVien instance);
    partial void DeleteUngVien(UngVien instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JobStarConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DoanhNghiep> DoanhNghieps
		{
			get
			{
				return this.GetTable<DoanhNghiep>();
			}
		}
		
		public System.Data.Linq.Table<UV_TTD> UV_TTDs
		{
			get
			{
				return this.GetTable<UV_TTD>();
			}
		}
		
		public System.Data.Linq.Table<FileND> FileNDs
		{
			get
			{
				return this.GetTable<FileND>();
			}
		}
		
		public System.Data.Linq.Table<GopY> Gopies
		{
			get
			{
				return this.GetTable<GopY>();
			}
		}
		
		public System.Data.Linq.Table<HoSoXinViec> HoSoXinViecs
		{
			get
			{
				return this.GetTable<HoSoXinViec>();
			}
		}
		
		public System.Data.Linq.Table<NhaTuyenDung> NhaTuyenDungs
		{
			get
			{
				return this.GetTable<NhaTuyenDung>();
			}
		}
		
		public System.Data.Linq.Table<PhiTinTuyenDung> PhiTinTuyenDungs
		{
			get
			{
				return this.GetTable<PhiTinTuyenDung>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TinTuyenDung> TinTuyenDungs
		{
			get
			{
				return this.GetTable<TinTuyenDung>();
			}
		}
		
		public System.Data.Linq.Table<UngVien> UngViens
		{
			get
			{
				return this.GetTable<UngVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhNghiep")]
	public partial class DoanhNghiep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_DN;
		
		private string _Ten_DN;
		
		private string _MaSoThue_DN;
		
		private string _LinkWeb_DN;
		
		private string _Logo_DN;
		
		private string _DiaDiem_DN;
		
		private string _MoTa_DN;
		
		private EntitySet<NhaTuyenDung> _NhaTuyenDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DNChanging(int value);
    partial void OnId_DNChanged();
    partial void OnTen_DNChanging(string value);
    partial void OnTen_DNChanged();
    partial void OnMaSoThue_DNChanging(string value);
    partial void OnMaSoThue_DNChanged();
    partial void OnLinkWeb_DNChanging(string value);
    partial void OnLinkWeb_DNChanged();
    partial void OnLogo_DNChanging(string value);
    partial void OnLogo_DNChanged();
    partial void OnDiaDiem_DNChanging(string value);
    partial void OnDiaDiem_DNChanged();
    partial void OnMoTa_DNChanging(string value);
    partial void OnMoTa_DNChanged();
    #endregion
		
		public DoanhNghiep()
		{
			this._NhaTuyenDungs = new EntitySet<NhaTuyenDung>(new Action<NhaTuyenDung>(this.attach_NhaTuyenDungs), new Action<NhaTuyenDung>(this.detach_NhaTuyenDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_DN
		{
			get
			{
				return this._Id_DN;
			}
			set
			{
				if ((this._Id_DN != value))
				{
					this.OnId_DNChanging(value);
					this.SendPropertyChanging();
					this._Id_DN = value;
					this.SendPropertyChanged("Id_DN");
					this.OnId_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_DN", DbType="NVarChar(MAX)")]
		public string Ten_DN
		{
			get
			{
				return this._Ten_DN;
			}
			set
			{
				if ((this._Ten_DN != value))
				{
					this.OnTen_DNChanging(value);
					this.SendPropertyChanging();
					this._Ten_DN = value;
					this.SendPropertyChanged("Ten_DN");
					this.OnTen_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoThue_DN", DbType="VarChar(30)")]
		public string MaSoThue_DN
		{
			get
			{
				return this._MaSoThue_DN;
			}
			set
			{
				if ((this._MaSoThue_DN != value))
				{
					this.OnMaSoThue_DNChanging(value);
					this.SendPropertyChanging();
					this._MaSoThue_DN = value;
					this.SendPropertyChanged("MaSoThue_DN");
					this.OnMaSoThue_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkWeb_DN", DbType="VarChar(MAX)")]
		public string LinkWeb_DN
		{
			get
			{
				return this._LinkWeb_DN;
			}
			set
			{
				if ((this._LinkWeb_DN != value))
				{
					this.OnLinkWeb_DNChanging(value);
					this.SendPropertyChanging();
					this._LinkWeb_DN = value;
					this.SendPropertyChanged("LinkWeb_DN");
					this.OnLinkWeb_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo_DN", DbType="NVarChar(MAX)")]
		public string Logo_DN
		{
			get
			{
				return this._Logo_DN;
			}
			set
			{
				if ((this._Logo_DN != value))
				{
					this.OnLogo_DNChanging(value);
					this.SendPropertyChanging();
					this._Logo_DN = value;
					this.SendPropertyChanged("Logo_DN");
					this.OnLogo_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem_DN", DbType="NVarChar(200)")]
		public string DiaDiem_DN
		{
			get
			{
				return this._DiaDiem_DN;
			}
			set
			{
				if ((this._DiaDiem_DN != value))
				{
					this.OnDiaDiem_DNChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem_DN = value;
					this.SendPropertyChanged("DiaDiem_DN");
					this.OnDiaDiem_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa_DN", DbType="NVarChar(MAX)")]
		public string MoTa_DN
		{
			get
			{
				return this._MoTa_DN;
			}
			set
			{
				if ((this._MoTa_DN != value))
				{
					this.OnMoTa_DNChanging(value);
					this.SendPropertyChanging();
					this._MoTa_DN = value;
					this.SendPropertyChanged("MoTa_DN");
					this.OnMoTa_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoanhNghiep_NhaTuyenDung", Storage="_NhaTuyenDungs", ThisKey="Id_DN", OtherKey="Id_DN")]
		public EntitySet<NhaTuyenDung> NhaTuyenDungs
		{
			get
			{
				return this._NhaTuyenDungs;
			}
			set
			{
				this._NhaTuyenDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.DoanhNghiep = this;
		}
		
		private void detach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.DoanhNghiep = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UV_TTD")]
	public partial class UV_TTD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_UT;
		
		private System.Nullable<int> _Id_UV;
		
		private System.Nullable<int> _Id_TTD;
		
		private System.Nullable<int> _Id_HSXV;
		
		private string _HoTenUV_TD;
		
		private string _EmailUV_TD;
		
		private string _SoDienThoaiUV_TD;
		
		private System.Nullable<System.DateTime> _ThoiGianUngTuyen;
		
		private string _TinhTrangUngTuyen;
		
		private string _File_CV;
		
		private string _NoiDung_ThuGioiThieu;
		
		private EntityRef<HoSoXinViec> _HoSoXinViec;
		
		private EntityRef<TinTuyenDung> _TinTuyenDung;
		
		private EntityRef<UngVien> _UngVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UTChanging(int value);
    partial void OnId_UTChanged();
    partial void OnId_UVChanging(System.Nullable<int> value);
    partial void OnId_UVChanged();
    partial void OnId_TTDChanging(System.Nullable<int> value);
    partial void OnId_TTDChanged();
    partial void OnId_HSXVChanging(System.Nullable<int> value);
    partial void OnId_HSXVChanged();
    partial void OnHoTenUV_TDChanging(string value);
    partial void OnHoTenUV_TDChanged();
    partial void OnEmailUV_TDChanging(string value);
    partial void OnEmailUV_TDChanged();
    partial void OnSoDienThoaiUV_TDChanging(string value);
    partial void OnSoDienThoaiUV_TDChanged();
    partial void OnThoiGianUngTuyenChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianUngTuyenChanged();
    partial void OnTinhTrangUngTuyenChanging(string value);
    partial void OnTinhTrangUngTuyenChanged();
    partial void OnFile_CVChanging(string value);
    partial void OnFile_CVChanged();
    partial void OnNoiDung_ThuGioiThieuChanging(string value);
    partial void OnNoiDung_ThuGioiThieuChanged();
    #endregion
		
		public UV_TTD()
		{
			this._HoSoXinViec = default(EntityRef<HoSoXinViec>);
			this._TinTuyenDung = default(EntityRef<TinTuyenDung>);
			this._UngVien = default(EntityRef<UngVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_UT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_UT
		{
			get
			{
				return this._Id_UT;
			}
			set
			{
				if ((this._Id_UT != value))
				{
					this.OnId_UTChanging(value);
					this.SendPropertyChanging();
					this._Id_UT = value;
					this.SendPropertyChanged("Id_UT");
					this.OnId_UTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_UV", DbType="Int")]
		public System.Nullable<int> Id_UV
		{
			get
			{
				return this._Id_UV;
			}
			set
			{
				if ((this._Id_UV != value))
				{
					if (this._UngVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UVChanging(value);
					this.SendPropertyChanging();
					this._Id_UV = value;
					this.SendPropertyChanged("Id_UV");
					this.OnId_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TTD", DbType="Int")]
		public System.Nullable<int> Id_TTD
		{
			get
			{
				return this._Id_TTD;
			}
			set
			{
				if ((this._Id_TTD != value))
				{
					if (this._TinTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TTDChanging(value);
					this.SendPropertyChanging();
					this._Id_TTD = value;
					this.SendPropertyChanged("Id_TTD");
					this.OnId_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_HSXV", DbType="Int")]
		public System.Nullable<int> Id_HSXV
		{
			get
			{
				return this._Id_HSXV;
			}
			set
			{
				if ((this._Id_HSXV != value))
				{
					if (this._HoSoXinViec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_HSXVChanging(value);
					this.SendPropertyChanging();
					this._Id_HSXV = value;
					this.SendPropertyChanged("Id_HSXV");
					this.OnId_HSXVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenUV_TD", DbType="NVarChar(100)")]
		public string HoTenUV_TD
		{
			get
			{
				return this._HoTenUV_TD;
			}
			set
			{
				if ((this._HoTenUV_TD != value))
				{
					this.OnHoTenUV_TDChanging(value);
					this.SendPropertyChanging();
					this._HoTenUV_TD = value;
					this.SendPropertyChanged("HoTenUV_TD");
					this.OnHoTenUV_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUV_TD", DbType="NVarChar(50)")]
		public string EmailUV_TD
		{
			get
			{
				return this._EmailUV_TD;
			}
			set
			{
				if ((this._EmailUV_TD != value))
				{
					this.OnEmailUV_TDChanging(value);
					this.SendPropertyChanging();
					this._EmailUV_TD = value;
					this.SendPropertyChanged("EmailUV_TD");
					this.OnEmailUV_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoaiUV_TD", DbType="VarChar(10)")]
		public string SoDienThoaiUV_TD
		{
			get
			{
				return this._SoDienThoaiUV_TD;
			}
			set
			{
				if ((this._SoDienThoaiUV_TD != value))
				{
					this.OnSoDienThoaiUV_TDChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoaiUV_TD = value;
					this.SendPropertyChanged("SoDienThoaiUV_TD");
					this.OnSoDienThoaiUV_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianUngTuyen", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianUngTuyen
		{
			get
			{
				return this._ThoiGianUngTuyen;
			}
			set
			{
				if ((this._ThoiGianUngTuyen != value))
				{
					this.OnThoiGianUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianUngTuyen = value;
					this.SendPropertyChanged("ThoiGianUngTuyen");
					this.OnThoiGianUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangUngTuyen", DbType="NVarChar(50)")]
		public string TinhTrangUngTuyen
		{
			get
			{
				return this._TinhTrangUngTuyen;
			}
			set
			{
				if ((this._TinhTrangUngTuyen != value))
				{
					this.OnTinhTrangUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangUngTuyen = value;
					this.SendPropertyChanged("TinhTrangUngTuyen");
					this.OnTinhTrangUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_File_CV", DbType="NVarChar(MAX)")]
		public string File_CV
		{
			get
			{
				return this._File_CV;
			}
			set
			{
				if ((this._File_CV != value))
				{
					this.OnFile_CVChanging(value);
					this.SendPropertyChanging();
					this._File_CV = value;
					this.SendPropertyChanged("File_CV");
					this.OnFile_CVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung_ThuGioiThieu", DbType="NVarChar(1000)")]
		public string NoiDung_ThuGioiThieu
		{
			get
			{
				return this._NoiDung_ThuGioiThieu;
			}
			set
			{
				if ((this._NoiDung_ThuGioiThieu != value))
				{
					this.OnNoiDung_ThuGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._NoiDung_ThuGioiThieu = value;
					this.SendPropertyChanged("NoiDung_ThuGioiThieu");
					this.OnNoiDung_ThuGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoXinViec_UV_TTD", Storage="_HoSoXinViec", ThisKey="Id_HSXV", OtherKey="Id_HSXV", IsForeignKey=true)]
		public HoSoXinViec HoSoXinViec
		{
			get
			{
				return this._HoSoXinViec.Entity;
			}
			set
			{
				HoSoXinViec previousValue = this._HoSoXinViec.Entity;
				if (((previousValue != value) 
							|| (this._HoSoXinViec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoXinViec.Entity = null;
						previousValue.UV_TTDs.Remove(this);
					}
					this._HoSoXinViec.Entity = value;
					if ((value != null))
					{
						value.UV_TTDs.Add(this);
						this._Id_HSXV = value.Id_HSXV;
					}
					else
					{
						this._Id_HSXV = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoSoXinViec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinTuyenDung_UV_TTD", Storage="_TinTuyenDung", ThisKey="Id_TTD", OtherKey="Id_TTD", IsForeignKey=true)]
		public TinTuyenDung TinTuyenDung
		{
			get
			{
				return this._TinTuyenDung.Entity;
			}
			set
			{
				TinTuyenDung previousValue = this._TinTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._TinTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinTuyenDung.Entity = null;
						previousValue.UV_TTDs.Remove(this);
					}
					this._TinTuyenDung.Entity = value;
					if ((value != null))
					{
						value.UV_TTDs.Add(this);
						this._Id_TTD = value.Id_TTD;
					}
					else
					{
						this._Id_TTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("TinTuyenDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_UV_TTD", Storage="_UngVien", ThisKey="Id_UV", OtherKey="Id_UV", IsForeignKey=true)]
		public UngVien UngVien
		{
			get
			{
				return this._UngVien.Entity;
			}
			set
			{
				UngVien previousValue = this._UngVien.Entity;
				if (((previousValue != value) 
							|| (this._UngVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UngVien.Entity = null;
						previousValue.UV_TTDs.Remove(this);
					}
					this._UngVien.Entity = value;
					if ((value != null))
					{
						value.UV_TTDs.Add(this);
						this._Id_UV = value.Id_UV;
					}
					else
					{
						this._Id_UV = default(Nullable<int>);
					}
					this.SendPropertyChanged("UngVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileND")]
	public partial class FileND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_File;
		
		private string _Nd_File;
		
		private System.Nullable<int> _Id_TTD;
		
		private EntityRef<TinTuyenDung> _TinTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FileChanging(int value);
    partial void OnId_FileChanged();
    partial void OnNd_FileChanging(string value);
    partial void OnNd_FileChanged();
    partial void OnId_TTDChanging(System.Nullable<int> value);
    partial void OnId_TTDChanged();
    #endregion
		
		public FileND()
		{
			this._TinTuyenDung = default(EntityRef<TinTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_File", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_File
		{
			get
			{
				return this._Id_File;
			}
			set
			{
				if ((this._Id_File != value))
				{
					this.OnId_FileChanging(value);
					this.SendPropertyChanging();
					this._Id_File = value;
					this.SendPropertyChanged("Id_File");
					this.OnId_FileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nd_File", DbType="NVarChar(MAX)")]
		public string Nd_File
		{
			get
			{
				return this._Nd_File;
			}
			set
			{
				if ((this._Nd_File != value))
				{
					this.OnNd_FileChanging(value);
					this.SendPropertyChanging();
					this._Nd_File = value;
					this.SendPropertyChanged("Nd_File");
					this.OnNd_FileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TTD", DbType="Int")]
		public System.Nullable<int> Id_TTD
		{
			get
			{
				return this._Id_TTD;
			}
			set
			{
				if ((this._Id_TTD != value))
				{
					if (this._TinTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TTDChanging(value);
					this.SendPropertyChanging();
					this._Id_TTD = value;
					this.SendPropertyChanged("Id_TTD");
					this.OnId_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinTuyenDung_FileND", Storage="_TinTuyenDung", ThisKey="Id_TTD", OtherKey="Id_TTD", IsForeignKey=true)]
		public TinTuyenDung TinTuyenDung
		{
			get
			{
				return this._TinTuyenDung.Entity;
			}
			set
			{
				TinTuyenDung previousValue = this._TinTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._TinTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinTuyenDung.Entity = null;
						previousValue.FileNDs.Remove(this);
					}
					this._TinTuyenDung.Entity = value;
					if ((value != null))
					{
						value.FileNDs.Add(this);
						this._Id_TTD = value.Id_TTD;
					}
					else
					{
						this._Id_TTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("TinTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GopY")]
	public partial class GopY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_GY;
		
		private string _TieuDe_GY;
		
		private string _NoiDung_GY;
		
		private System.Nullable<short> _MucDoHaiLong;
		
		private System.Nullable<System.DateTime> _NgayGui_GY;
		
		private System.Nullable<int> _Id_UV;
		
		private System.Nullable<int> _Id_NTD;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;
		
		private EntityRef<UngVien> _UngVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_GYChanging(int value);
    partial void OnId_GYChanged();
    partial void OnTieuDe_GYChanging(string value);
    partial void OnTieuDe_GYChanged();
    partial void OnNoiDung_GYChanging(string value);
    partial void OnNoiDung_GYChanged();
    partial void OnMucDoHaiLongChanging(System.Nullable<short> value);
    partial void OnMucDoHaiLongChanged();
    partial void OnNgayGui_GYChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGui_GYChanged();
    partial void OnId_UVChanging(System.Nullable<int> value);
    partial void OnId_UVChanged();
    partial void OnId_NTDChanging(System.Nullable<int> value);
    partial void OnId_NTDChanged();
    #endregion
		
		public GopY()
		{
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			this._UngVien = default(EntityRef<UngVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_GY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_GY
		{
			get
			{
				return this._Id_GY;
			}
			set
			{
				if ((this._Id_GY != value))
				{
					this.OnId_GYChanging(value);
					this.SendPropertyChanging();
					this._Id_GY = value;
					this.SendPropertyChanged("Id_GY");
					this.OnId_GYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe_GY", DbType="NVarChar(100)")]
		public string TieuDe_GY
		{
			get
			{
				return this._TieuDe_GY;
			}
			set
			{
				if ((this._TieuDe_GY != value))
				{
					this.OnTieuDe_GYChanging(value);
					this.SendPropertyChanging();
					this._TieuDe_GY = value;
					this.SendPropertyChanged("TieuDe_GY");
					this.OnTieuDe_GYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung_GY", DbType="NVarChar(100)")]
		public string NoiDung_GY
		{
			get
			{
				return this._NoiDung_GY;
			}
			set
			{
				if ((this._NoiDung_GY != value))
				{
					this.OnNoiDung_GYChanging(value);
					this.SendPropertyChanging();
					this._NoiDung_GY = value;
					this.SendPropertyChanged("NoiDung_GY");
					this.OnNoiDung_GYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucDoHaiLong", DbType="SmallInt")]
		public System.Nullable<short> MucDoHaiLong
		{
			get
			{
				return this._MucDoHaiLong;
			}
			set
			{
				if ((this._MucDoHaiLong != value))
				{
					this.OnMucDoHaiLongChanging(value);
					this.SendPropertyChanging();
					this._MucDoHaiLong = value;
					this.SendPropertyChanged("MucDoHaiLong");
					this.OnMucDoHaiLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui_GY", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGui_GY
		{
			get
			{
				return this._NgayGui_GY;
			}
			set
			{
				if ((this._NgayGui_GY != value))
				{
					this.OnNgayGui_GYChanging(value);
					this.SendPropertyChanging();
					this._NgayGui_GY = value;
					this.SendPropertyChanged("NgayGui_GY");
					this.OnNgayGui_GYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_UV", DbType="Int")]
		public System.Nullable<int> Id_UV
		{
			get
			{
				return this._Id_UV;
			}
			set
			{
				if ((this._Id_UV != value))
				{
					if (this._UngVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UVChanging(value);
					this.SendPropertyChanging();
					this._Id_UV = value;
					this.SendPropertyChanged("Id_UV");
					this.OnId_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NTD", DbType="Int")]
		public System.Nullable<int> Id_NTD
		{
			get
			{
				return this._Id_NTD;
			}
			set
			{
				if ((this._Id_NTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_NTDChanging(value);
					this.SendPropertyChanging();
					this._Id_NTD = value;
					this.SendPropertyChanged("Id_NTD");
					this.OnId_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_GopY", Storage="_NhaTuyenDung", ThisKey="Id_NTD", OtherKey="Id_NTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.Gopies.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.Gopies.Add(this);
						this._Id_NTD = value.Id_NTD;
					}
					else
					{
						this._Id_NTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_GopY", Storage="_UngVien", ThisKey="Id_UV", OtherKey="Id_UV", IsForeignKey=true)]
		public UngVien UngVien
		{
			get
			{
				return this._UngVien.Entity;
			}
			set
			{
				UngVien previousValue = this._UngVien.Entity;
				if (((previousValue != value) 
							|| (this._UngVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UngVien.Entity = null;
						previousValue.Gopies.Remove(this);
					}
					this._UngVien.Entity = value;
					if ((value != null))
					{
						value.Gopies.Add(this);
						this._Id_UV = value.Id_UV;
					}
					else
					{
						this._Id_UV = default(Nullable<int>);
					}
					this.SendPropertyChanged("UngVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoSoXinViec")]
	public partial class HoSoXinViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_HSXV;
		
		private string _Ten_HSXV;
		
		private System.Nullable<System.DateTime> _TGCN_HSXV;
		
		private System.Nullable<int> _Id_UV;
		
		private string _HoTenUV;
		
		private string _EmailUV;
		
		private string _SoDienThoaiUV;
		
		private string _File_HSXV;
		
		private EntitySet<UV_TTD> _UV_TTDs;
		
		private EntityRef<UngVien> _UngVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_HSXVChanging(int value);
    partial void OnId_HSXVChanged();
    partial void OnTen_HSXVChanging(string value);
    partial void OnTen_HSXVChanged();
    partial void OnTGCN_HSXVChanging(System.Nullable<System.DateTime> value);
    partial void OnTGCN_HSXVChanged();
    partial void OnId_UVChanging(System.Nullable<int> value);
    partial void OnId_UVChanged();
    partial void OnHoTenUVChanging(string value);
    partial void OnHoTenUVChanged();
    partial void OnEmailUVChanging(string value);
    partial void OnEmailUVChanged();
    partial void OnSoDienThoaiUVChanging(string value);
    partial void OnSoDienThoaiUVChanged();
    partial void OnFile_HSXVChanging(string value);
    partial void OnFile_HSXVChanged();
    #endregion
		
		public HoSoXinViec()
		{
			this._UV_TTDs = new EntitySet<UV_TTD>(new Action<UV_TTD>(this.attach_UV_TTDs), new Action<UV_TTD>(this.detach_UV_TTDs));
			this._UngVien = default(EntityRef<UngVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_HSXV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_HSXV
		{
			get
			{
				return this._Id_HSXV;
			}
			set
			{
				if ((this._Id_HSXV != value))
				{
					this.OnId_HSXVChanging(value);
					this.SendPropertyChanging();
					this._Id_HSXV = value;
					this.SendPropertyChanged("Id_HSXV");
					this.OnId_HSXVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_HSXV", DbType="NVarChar(50)")]
		public string Ten_HSXV
		{
			get
			{
				return this._Ten_HSXV;
			}
			set
			{
				if ((this._Ten_HSXV != value))
				{
					this.OnTen_HSXVChanging(value);
					this.SendPropertyChanging();
					this._Ten_HSXV = value;
					this.SendPropertyChanged("Ten_HSXV");
					this.OnTen_HSXVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGCN_HSXV", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGCN_HSXV
		{
			get
			{
				return this._TGCN_HSXV;
			}
			set
			{
				if ((this._TGCN_HSXV != value))
				{
					this.OnTGCN_HSXVChanging(value);
					this.SendPropertyChanging();
					this._TGCN_HSXV = value;
					this.SendPropertyChanged("TGCN_HSXV");
					this.OnTGCN_HSXVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_UV", DbType="Int")]
		public System.Nullable<int> Id_UV
		{
			get
			{
				return this._Id_UV;
			}
			set
			{
				if ((this._Id_UV != value))
				{
					if (this._UngVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UVChanging(value);
					this.SendPropertyChanging();
					this._Id_UV = value;
					this.SendPropertyChanged("Id_UV");
					this.OnId_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenUV", DbType="NVarChar(100)")]
		public string HoTenUV
		{
			get
			{
				return this._HoTenUV;
			}
			set
			{
				if ((this._HoTenUV != value))
				{
					this.OnHoTenUVChanging(value);
					this.SendPropertyChanging();
					this._HoTenUV = value;
					this.SendPropertyChanged("HoTenUV");
					this.OnHoTenUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUV", DbType="NVarChar(50)")]
		public string EmailUV
		{
			get
			{
				return this._EmailUV;
			}
			set
			{
				if ((this._EmailUV != value))
				{
					this.OnEmailUVChanging(value);
					this.SendPropertyChanging();
					this._EmailUV = value;
					this.SendPropertyChanged("EmailUV");
					this.OnEmailUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoaiUV", DbType="VarChar(10)")]
		public string SoDienThoaiUV
		{
			get
			{
				return this._SoDienThoaiUV;
			}
			set
			{
				if ((this._SoDienThoaiUV != value))
				{
					this.OnSoDienThoaiUVChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoaiUV = value;
					this.SendPropertyChanged("SoDienThoaiUV");
					this.OnSoDienThoaiUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_File_HSXV", DbType="NVarChar(MAX)")]
		public string File_HSXV
		{
			get
			{
				return this._File_HSXV;
			}
			set
			{
				if ((this._File_HSXV != value))
				{
					this.OnFile_HSXVChanging(value);
					this.SendPropertyChanging();
					this._File_HSXV = value;
					this.SendPropertyChanged("File_HSXV");
					this.OnFile_HSXVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoXinViec_UV_TTD", Storage="_UV_TTDs", ThisKey="Id_HSXV", OtherKey="Id_HSXV")]
		public EntitySet<UV_TTD> UV_TTDs
		{
			get
			{
				return this._UV_TTDs;
			}
			set
			{
				this._UV_TTDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_HoSoXinViec", Storage="_UngVien", ThisKey="Id_UV", OtherKey="Id_UV", IsForeignKey=true)]
		public UngVien UngVien
		{
			get
			{
				return this._UngVien.Entity;
			}
			set
			{
				UngVien previousValue = this._UngVien.Entity;
				if (((previousValue != value) 
							|| (this._UngVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UngVien.Entity = null;
						previousValue.HoSoXinViecs.Remove(this);
					}
					this._UngVien.Entity = value;
					if ((value != null))
					{
						value.HoSoXinViecs.Add(this);
						this._Id_UV = value.Id_UV;
					}
					else
					{
						this._Id_UV = default(Nullable<int>);
					}
					this.SendPropertyChanged("UngVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.HoSoXinViec = this;
		}
		
		private void detach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.HoSoXinViec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaTuyenDung")]
	public partial class NhaTuyenDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_NTD;
		
		private string _HoTen_NTD;
		
		private string _SoDienThoai_NTD;
		
		private string _Email_NTD;
		
		private string _HinhAnh_NTD;
		
		private string _ViTriCongTac;
		
		private System.Nullable<int> _Id_DN;
		
		private string _TenTK;
		
		private EntitySet<GopY> _Gopies;
		
		private EntitySet<TinTuyenDung> _TinTuyenDungs;
		
		private EntityRef<DoanhNghiep> _DoanhNghiep;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_NTDChanging(int value);
    partial void OnId_NTDChanged();
    partial void OnHoTen_NTDChanging(string value);
    partial void OnHoTen_NTDChanged();
    partial void OnSoDienThoai_NTDChanging(string value);
    partial void OnSoDienThoai_NTDChanged();
    partial void OnEmail_NTDChanging(string value);
    partial void OnEmail_NTDChanged();
    partial void OnHinhAnh_NTDChanging(string value);
    partial void OnHinhAnh_NTDChanged();
    partial void OnViTriCongTacChanging(string value);
    partial void OnViTriCongTacChanged();
    partial void OnId_DNChanging(System.Nullable<int> value);
    partial void OnId_DNChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    #endregion
		
		public NhaTuyenDung()
		{
			this._Gopies = new EntitySet<GopY>(new Action<GopY>(this.attach_Gopies), new Action<GopY>(this.detach_Gopies));
			this._TinTuyenDungs = new EntitySet<TinTuyenDung>(new Action<TinTuyenDung>(this.attach_TinTuyenDungs), new Action<TinTuyenDung>(this.detach_TinTuyenDungs));
			this._DoanhNghiep = default(EntityRef<DoanhNghiep>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_NTD
		{
			get
			{
				return this._Id_NTD;
			}
			set
			{
				if ((this._Id_NTD != value))
				{
					this.OnId_NTDChanging(value);
					this.SendPropertyChanging();
					this._Id_NTD = value;
					this.SendPropertyChanged("Id_NTD");
					this.OnId_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen_NTD", DbType="NVarChar(100)")]
		public string HoTen_NTD
		{
			get
			{
				return this._HoTen_NTD;
			}
			set
			{
				if ((this._HoTen_NTD != value))
				{
					this.OnHoTen_NTDChanging(value);
					this.SendPropertyChanging();
					this._HoTen_NTD = value;
					this.SendPropertyChanged("HoTen_NTD");
					this.OnHoTen_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai_NTD", DbType="VarChar(10)")]
		public string SoDienThoai_NTD
		{
			get
			{
				return this._SoDienThoai_NTD;
			}
			set
			{
				if ((this._SoDienThoai_NTD != value))
				{
					this.OnSoDienThoai_NTDChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai_NTD = value;
					this.SendPropertyChanged("SoDienThoai_NTD");
					this.OnSoDienThoai_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_NTD", DbType="VarChar(50)")]
		public string Email_NTD
		{
			get
			{
				return this._Email_NTD;
			}
			set
			{
				if ((this._Email_NTD != value))
				{
					this.OnEmail_NTDChanging(value);
					this.SendPropertyChanging();
					this._Email_NTD = value;
					this.SendPropertyChanged("Email_NTD");
					this.OnEmail_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh_NTD", DbType="VarChar(MAX)")]
		public string HinhAnh_NTD
		{
			get
			{
				return this._HinhAnh_NTD;
			}
			set
			{
				if ((this._HinhAnh_NTD != value))
				{
					this.OnHinhAnh_NTDChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh_NTD = value;
					this.SendPropertyChanged("HinhAnh_NTD");
					this.OnHinhAnh_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTriCongTac", DbType="NVarChar(100)")]
		public string ViTriCongTac
		{
			get
			{
				return this._ViTriCongTac;
			}
			set
			{
				if ((this._ViTriCongTac != value))
				{
					this.OnViTriCongTacChanging(value);
					this.SendPropertyChanging();
					this._ViTriCongTac = value;
					this.SendPropertyChanged("ViTriCongTac");
					this.OnViTriCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DN", DbType="Int")]
		public System.Nullable<int> Id_DN
		{
			get
			{
				return this._Id_DN;
			}
			set
			{
				if ((this._Id_DN != value))
				{
					if (this._DoanhNghiep.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_DNChanging(value);
					this.SendPropertyChanging();
					this._Id_DN = value;
					this.SendPropertyChanged("Id_DN");
					this.OnId_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="VarChar(50)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_GopY", Storage="_Gopies", ThisKey="Id_NTD", OtherKey="Id_NTD")]
		public EntitySet<GopY> Gopies
		{
			get
			{
				return this._Gopies;
			}
			set
			{
				this._Gopies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_TinTuyenDung", Storage="_TinTuyenDungs", ThisKey="Id_NTD", OtherKey="Id_NTD")]
		public EntitySet<TinTuyenDung> TinTuyenDungs
		{
			get
			{
				return this._TinTuyenDungs;
			}
			set
			{
				this._TinTuyenDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoanhNghiep_NhaTuyenDung", Storage="_DoanhNghiep", ThisKey="Id_DN", OtherKey="Id_DN", IsForeignKey=true)]
		public DoanhNghiep DoanhNghiep
		{
			get
			{
				return this._DoanhNghiep.Entity;
			}
			set
			{
				DoanhNghiep previousValue = this._DoanhNghiep.Entity;
				if (((previousValue != value) 
							|| (this._DoanhNghiep.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoanhNghiep.Entity = null;
						previousValue.NhaTuyenDungs.Remove(this);
					}
					this._DoanhNghiep.Entity = value;
					if ((value != null))
					{
						value.NhaTuyenDungs.Add(this);
						this._Id_DN = value.Id_DN;
					}
					else
					{
						this._Id_DN = default(Nullable<int>);
					}
					this.SendPropertyChanged("DoanhNghiep");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhaTuyenDung", Storage="_TaiKhoan", ThisKey="TenTK", OtherKey="TenTK", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhaTuyenDungs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhaTuyenDungs.Add(this);
						this._TenTK = value.TenTK;
					}
					else
					{
						this._TenTK = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gopies(GopY entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_Gopies(GopY entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
		
		private void attach_TinTuyenDungs(TinTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_TinTuyenDungs(TinTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhiTinTuyenDung")]
	public partial class PhiTinTuyenDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_PTTD;
		
		private System.Nullable<int> _Gia_PTTD;
		
		private System.Nullable<bool> _ApDungPhi;
		
		private EntitySet<TinTuyenDung> _TinTuyenDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PTTDChanging(int value);
    partial void OnId_PTTDChanged();
    partial void OnGia_PTTDChanging(System.Nullable<int> value);
    partial void OnGia_PTTDChanged();
    partial void OnApDungPhiChanging(System.Nullable<bool> value);
    partial void OnApDungPhiChanged();
    #endregion
		
		public PhiTinTuyenDung()
		{
			this._TinTuyenDungs = new EntitySet<TinTuyenDung>(new Action<TinTuyenDung>(this.attach_TinTuyenDungs), new Action<TinTuyenDung>(this.detach_TinTuyenDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PTTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_PTTD
		{
			get
			{
				return this._Id_PTTD;
			}
			set
			{
				if ((this._Id_PTTD != value))
				{
					this.OnId_PTTDChanging(value);
					this.SendPropertyChanging();
					this._Id_PTTD = value;
					this.SendPropertyChanged("Id_PTTD");
					this.OnId_PTTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia_PTTD", DbType="Int")]
		public System.Nullable<int> Gia_PTTD
		{
			get
			{
				return this._Gia_PTTD;
			}
			set
			{
				if ((this._Gia_PTTD != value))
				{
					this.OnGia_PTTDChanging(value);
					this.SendPropertyChanging();
					this._Gia_PTTD = value;
					this.SendPropertyChanged("Gia_PTTD");
					this.OnGia_PTTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApDungPhi", DbType="Bit")]
		public System.Nullable<bool> ApDungPhi
		{
			get
			{
				return this._ApDungPhi;
			}
			set
			{
				if ((this._ApDungPhi != value))
				{
					this.OnApDungPhiChanging(value);
					this.SendPropertyChanging();
					this._ApDungPhi = value;
					this.SendPropertyChanged("ApDungPhi");
					this.OnApDungPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhiTinTuyenDung_TinTuyenDung", Storage="_TinTuyenDungs", ThisKey="Id_PTTD", OtherKey="Id_PTTD")]
		public EntitySet<TinTuyenDung> TinTuyenDungs
		{
			get
			{
				return this._TinTuyenDungs;
			}
			set
			{
				this._TinTuyenDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TinTuyenDungs(TinTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.PhiTinTuyenDung = this;
		}
		
		private void detach_TinTuyenDungs(TinTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.PhiTinTuyenDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTK;
		
		private string _MatKhau;
		
		private EntitySet<NhaTuyenDung> _NhaTuyenDungs;
		
		private EntitySet<UngVien> _UngViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhaTuyenDungs = new EntitySet<NhaTuyenDung>(new Action<NhaTuyenDung>(this.attach_NhaTuyenDungs), new Action<NhaTuyenDung>(this.detach_NhaTuyenDungs));
			this._UngViens = new EntitySet<UngVien>(new Action<UngVien>(this.attach_UngViens), new Action<UngVien>(this.detach_UngViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(MAX)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhaTuyenDung", Storage="_NhaTuyenDungs", ThisKey="TenTK", OtherKey="TenTK")]
		public EntitySet<NhaTuyenDung> NhaTuyenDungs
		{
			get
			{
				return this._NhaTuyenDungs;
			}
			set
			{
				this._NhaTuyenDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_UngVien", Storage="_UngViens", ThisKey="TenTK", OtherKey="TenTK")]
		public EntitySet<UngVien> UngViens
		{
			get
			{
				return this._UngViens;
			}
			set
			{
				this._UngViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_UngViens(UngVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_UngViens(UngVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuyenDung")]
	public partial class TinTuyenDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_TTD;
		
		private string _TieuDe_TTD;
		
		private System.Nullable<System.DateTime> _HanTuyenDung;
		
		private string _MucLuongTD;
		
		private string _YeuCauGioiTinh;
		
		private string _CapBacTD;
		
		private System.Nullable<int> _SoLuongTuyen;
		
		private string _HinhThucLamViec;
		
		private System.Nullable<bool> _TrangThaiDang;
		
		private System.Nullable<System.DateTime> _ThoiGianDangTuyen;
		
		private System.Nullable<bool> _TinhPhi_TTD;
		
		private string _DiaDiem_TTD;
		
		private string _Logo_DN_TTD;
		
		private string _MoTa_TTD;
		
		private string _XetDuyet;
		
		private string _KinhNghiemLam;
		
		private System.Nullable<int> _Id_NTD;
		
		private System.Nullable<int> _Id_PTTD;
		
		private EntitySet<UV_TTD> _UV_TTDs;
		
		private EntitySet<FileND> _FileNDs;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;
		
		private EntityRef<PhiTinTuyenDung> _PhiTinTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TTDChanging(int value);
    partial void OnId_TTDChanged();
    partial void OnTieuDe_TTDChanging(string value);
    partial void OnTieuDe_TTDChanged();
    partial void OnHanTuyenDungChanging(System.Nullable<System.DateTime> value);
    partial void OnHanTuyenDungChanged();
    partial void OnMucLuongTDChanging(string value);
    partial void OnMucLuongTDChanged();
    partial void OnYeuCauGioiTinhChanging(string value);
    partial void OnYeuCauGioiTinhChanged();
    partial void OnCapBacTDChanging(string value);
    partial void OnCapBacTDChanged();
    partial void OnSoLuongTuyenChanging(System.Nullable<int> value);
    partial void OnSoLuongTuyenChanged();
    partial void OnHinhThucLamViecChanging(string value);
    partial void OnHinhThucLamViecChanged();
    partial void OnTrangThaiDangChanging(System.Nullable<bool> value);
    partial void OnTrangThaiDangChanged();
    partial void OnThoiGianDangTuyenChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDangTuyenChanged();
    partial void OnTinhPhi_TTDChanging(System.Nullable<bool> value);
    partial void OnTinhPhi_TTDChanged();
    partial void OnDiaDiem_TTDChanging(string value);
    partial void OnDiaDiem_TTDChanged();
    partial void OnLogo_DN_TTDChanging(string value);
    partial void OnLogo_DN_TTDChanged();
    partial void OnMoTa_TTDChanging(string value);
    partial void OnMoTa_TTDChanged();
    partial void OnXetDuyetChanging(string value);
    partial void OnXetDuyetChanged();
    partial void OnKinhNghiemLamChanging(string value);
    partial void OnKinhNghiemLamChanged();
    partial void OnId_NTDChanging(System.Nullable<int> value);
    partial void OnId_NTDChanged();
    partial void OnId_PTTDChanging(System.Nullable<int> value);
    partial void OnId_PTTDChanged();
    #endregion
		
		public TinTuyenDung()
		{
			this._UV_TTDs = new EntitySet<UV_TTD>(new Action<UV_TTD>(this.attach_UV_TTDs), new Action<UV_TTD>(this.detach_UV_TTDs));
			this._FileNDs = new EntitySet<FileND>(new Action<FileND>(this.attach_FileNDs), new Action<FileND>(this.detach_FileNDs));
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			this._PhiTinTuyenDung = default(EntityRef<PhiTinTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_TTD
		{
			get
			{
				return this._Id_TTD;
			}
			set
			{
				if ((this._Id_TTD != value))
				{
					this.OnId_TTDChanging(value);
					this.SendPropertyChanging();
					this._Id_TTD = value;
					this.SendPropertyChanged("Id_TTD");
					this.OnId_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe_TTD", DbType="NVarChar(MAX)")]
		public string TieuDe_TTD
		{
			get
			{
				return this._TieuDe_TTD;
			}
			set
			{
				if ((this._TieuDe_TTD != value))
				{
					this.OnTieuDe_TTDChanging(value);
					this.SendPropertyChanging();
					this._TieuDe_TTD = value;
					this.SendPropertyChanged("TieuDe_TTD");
					this.OnTieuDe_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanTuyenDung", DbType="Date")]
		public System.Nullable<System.DateTime> HanTuyenDung
		{
			get
			{
				return this._HanTuyenDung;
			}
			set
			{
				if ((this._HanTuyenDung != value))
				{
					this.OnHanTuyenDungChanging(value);
					this.SendPropertyChanging();
					this._HanTuyenDung = value;
					this.SendPropertyChanged("HanTuyenDung");
					this.OnHanTuyenDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuongTD", DbType="NVarChar(50)")]
		public string MucLuongTD
		{
			get
			{
				return this._MucLuongTD;
			}
			set
			{
				if ((this._MucLuongTD != value))
				{
					this.OnMucLuongTDChanging(value);
					this.SendPropertyChanging();
					this._MucLuongTD = value;
					this.SendPropertyChanged("MucLuongTD");
					this.OnMucLuongTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGioiTinh", DbType="NVarChar(100)")]
		public string YeuCauGioiTinh
		{
			get
			{
				return this._YeuCauGioiTinh;
			}
			set
			{
				if ((this._YeuCauGioiTinh != value))
				{
					this.OnYeuCauGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._YeuCauGioiTinh = value;
					this.SendPropertyChanged("YeuCauGioiTinh");
					this.OnYeuCauGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBacTD", DbType="NVarChar(30)")]
		public string CapBacTD
		{
			get
			{
				return this._CapBacTD;
			}
			set
			{
				if ((this._CapBacTD != value))
				{
					this.OnCapBacTDChanging(value);
					this.SendPropertyChanging();
					this._CapBacTD = value;
					this.SendPropertyChanged("CapBacTD");
					this.OnCapBacTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTuyen", DbType="Int")]
		public System.Nullable<int> SoLuongTuyen
		{
			get
			{
				return this._SoLuongTuyen;
			}
			set
			{
				if ((this._SoLuongTuyen != value))
				{
					this.OnSoLuongTuyenChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTuyen = value;
					this.SendPropertyChanged("SoLuongTuyen");
					this.OnSoLuongTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucLamViec", DbType="NVarChar(30)")]
		public string HinhThucLamViec
		{
			get
			{
				return this._HinhThucLamViec;
			}
			set
			{
				if ((this._HinhThucLamViec != value))
				{
					this.OnHinhThucLamViecChanging(value);
					this.SendPropertyChanging();
					this._HinhThucLamViec = value;
					this.SendPropertyChanged("HinhThucLamViec");
					this.OnHinhThucLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDang", DbType="Bit")]
		public System.Nullable<bool> TrangThaiDang
		{
			get
			{
				return this._TrangThaiDang;
			}
			set
			{
				if ((this._TrangThaiDang != value))
				{
					this.OnTrangThaiDangChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDang = value;
					this.SendPropertyChanged("TrangThaiDang");
					this.OnTrangThaiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangTuyen", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangTuyen
		{
			get
			{
				return this._ThoiGianDangTuyen;
			}
			set
			{
				if ((this._ThoiGianDangTuyen != value))
				{
					this.OnThoiGianDangTuyenChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDangTuyen = value;
					this.SendPropertyChanged("ThoiGianDangTuyen");
					this.OnThoiGianDangTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhPhi_TTD", DbType="Bit")]
		public System.Nullable<bool> TinhPhi_TTD
		{
			get
			{
				return this._TinhPhi_TTD;
			}
			set
			{
				if ((this._TinhPhi_TTD != value))
				{
					this.OnTinhPhi_TTDChanging(value);
					this.SendPropertyChanging();
					this._TinhPhi_TTD = value;
					this.SendPropertyChanged("TinhPhi_TTD");
					this.OnTinhPhi_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem_TTD", DbType="NVarChar(300)")]
		public string DiaDiem_TTD
		{
			get
			{
				return this._DiaDiem_TTD;
			}
			set
			{
				if ((this._DiaDiem_TTD != value))
				{
					this.OnDiaDiem_TTDChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem_TTD = value;
					this.SendPropertyChanged("DiaDiem_TTD");
					this.OnDiaDiem_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo_DN_TTD", DbType="NVarChar(MAX)")]
		public string Logo_DN_TTD
		{
			get
			{
				return this._Logo_DN_TTD;
			}
			set
			{
				if ((this._Logo_DN_TTD != value))
				{
					this.OnLogo_DN_TTDChanging(value);
					this.SendPropertyChanging();
					this._Logo_DN_TTD = value;
					this.SendPropertyChanged("Logo_DN_TTD");
					this.OnLogo_DN_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa_TTD", DbType="NVarChar(MAX)")]
		public string MoTa_TTD
		{
			get
			{
				return this._MoTa_TTD;
			}
			set
			{
				if ((this._MoTa_TTD != value))
				{
					this.OnMoTa_TTDChanging(value);
					this.SendPropertyChanging();
					this._MoTa_TTD = value;
					this.SendPropertyChanged("MoTa_TTD");
					this.OnMoTa_TTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XetDuyet", DbType="NVarChar(50)")]
		public string XetDuyet
		{
			get
			{
				return this._XetDuyet;
			}
			set
			{
				if ((this._XetDuyet != value))
				{
					this.OnXetDuyetChanging(value);
					this.SendPropertyChanging();
					this._XetDuyet = value;
					this.SendPropertyChanged("XetDuyet");
					this.OnXetDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhNghiemLam", DbType="NVarChar(100)")]
		public string KinhNghiemLam
		{
			get
			{
				return this._KinhNghiemLam;
			}
			set
			{
				if ((this._KinhNghiemLam != value))
				{
					this.OnKinhNghiemLamChanging(value);
					this.SendPropertyChanging();
					this._KinhNghiemLam = value;
					this.SendPropertyChanged("KinhNghiemLam");
					this.OnKinhNghiemLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NTD", DbType="Int")]
		public System.Nullable<int> Id_NTD
		{
			get
			{
				return this._Id_NTD;
			}
			set
			{
				if ((this._Id_NTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_NTDChanging(value);
					this.SendPropertyChanging();
					this._Id_NTD = value;
					this.SendPropertyChanged("Id_NTD");
					this.OnId_NTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PTTD", DbType="Int")]
		public System.Nullable<int> Id_PTTD
		{
			get
			{
				return this._Id_PTTD;
			}
			set
			{
				if ((this._Id_PTTD != value))
				{
					if (this._PhiTinTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PTTDChanging(value);
					this.SendPropertyChanging();
					this._Id_PTTD = value;
					this.SendPropertyChanged("Id_PTTD");
					this.OnId_PTTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinTuyenDung_UV_TTD", Storage="_UV_TTDs", ThisKey="Id_TTD", OtherKey="Id_TTD")]
		public EntitySet<UV_TTD> UV_TTDs
		{
			get
			{
				return this._UV_TTDs;
			}
			set
			{
				this._UV_TTDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinTuyenDung_FileND", Storage="_FileNDs", ThisKey="Id_TTD", OtherKey="Id_TTD")]
		public EntitySet<FileND> FileNDs
		{
			get
			{
				return this._FileNDs;
			}
			set
			{
				this._FileNDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_TinTuyenDung", Storage="_NhaTuyenDung", ThisKey="Id_NTD", OtherKey="Id_NTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.TinTuyenDungs.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.TinTuyenDungs.Add(this);
						this._Id_NTD = value.Id_NTD;
					}
					else
					{
						this._Id_NTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhiTinTuyenDung_TinTuyenDung", Storage="_PhiTinTuyenDung", ThisKey="Id_PTTD", OtherKey="Id_PTTD", IsForeignKey=true)]
		public PhiTinTuyenDung PhiTinTuyenDung
		{
			get
			{
				return this._PhiTinTuyenDung.Entity;
			}
			set
			{
				PhiTinTuyenDung previousValue = this._PhiTinTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._PhiTinTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhiTinTuyenDung.Entity = null;
						previousValue.TinTuyenDungs.Remove(this);
					}
					this._PhiTinTuyenDung.Entity = value;
					if ((value != null))
					{
						value.TinTuyenDungs.Add(this);
						this._Id_PTTD = value.Id_PTTD;
					}
					else
					{
						this._Id_PTTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhiTinTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.TinTuyenDung = this;
		}
		
		private void detach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.TinTuyenDung = null;
		}
		
		private void attach_FileNDs(FileND entity)
		{
			this.SendPropertyChanging();
			entity.TinTuyenDung = this;
		}
		
		private void detach_FileNDs(FileND entity)
		{
			this.SendPropertyChanging();
			entity.TinTuyenDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UngVien")]
	public partial class UngVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_UV;
		
		private string _HoTen_TKUV;
		
		private string _Email_TKUV;
		
		private string _HinhAnhTKUV;
		
		private string _SoDienThoai_TKUV;
		
		private string _TenTK;
		
		private EntitySet<UV_TTD> _UV_TTDs;
		
		private EntitySet<GopY> _Gopies;
		
		private EntitySet<HoSoXinViec> _HoSoXinViecs;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UVChanging(int value);
    partial void OnId_UVChanged();
    partial void OnHoTen_TKUVChanging(string value);
    partial void OnHoTen_TKUVChanged();
    partial void OnEmail_TKUVChanging(string value);
    partial void OnEmail_TKUVChanged();
    partial void OnHinhAnhTKUVChanging(string value);
    partial void OnHinhAnhTKUVChanged();
    partial void OnSoDienThoai_TKUVChanging(string value);
    partial void OnSoDienThoai_TKUVChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    #endregion
		
		public UngVien()
		{
			this._UV_TTDs = new EntitySet<UV_TTD>(new Action<UV_TTD>(this.attach_UV_TTDs), new Action<UV_TTD>(this.detach_UV_TTDs));
			this._Gopies = new EntitySet<GopY>(new Action<GopY>(this.attach_Gopies), new Action<GopY>(this.detach_Gopies));
			this._HoSoXinViecs = new EntitySet<HoSoXinViec>(new Action<HoSoXinViec>(this.attach_HoSoXinViecs), new Action<HoSoXinViec>(this.detach_HoSoXinViecs));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_UV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_UV
		{
			get
			{
				return this._Id_UV;
			}
			set
			{
				if ((this._Id_UV != value))
				{
					this.OnId_UVChanging(value);
					this.SendPropertyChanging();
					this._Id_UV = value;
					this.SendPropertyChanged("Id_UV");
					this.OnId_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen_TKUV", DbType="NVarChar(100)")]
		public string HoTen_TKUV
		{
			get
			{
				return this._HoTen_TKUV;
			}
			set
			{
				if ((this._HoTen_TKUV != value))
				{
					this.OnHoTen_TKUVChanging(value);
					this.SendPropertyChanging();
					this._HoTen_TKUV = value;
					this.SendPropertyChanged("HoTen_TKUV");
					this.OnHoTen_TKUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_TKUV", DbType="VarChar(50)")]
		public string Email_TKUV
		{
			get
			{
				return this._Email_TKUV;
			}
			set
			{
				if ((this._Email_TKUV != value))
				{
					this.OnEmail_TKUVChanging(value);
					this.SendPropertyChanging();
					this._Email_TKUV = value;
					this.SendPropertyChanged("Email_TKUV");
					this.OnEmail_TKUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhTKUV", DbType="NVarChar(MAX)")]
		public string HinhAnhTKUV
		{
			get
			{
				return this._HinhAnhTKUV;
			}
			set
			{
				if ((this._HinhAnhTKUV != value))
				{
					this.OnHinhAnhTKUVChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhTKUV = value;
					this.SendPropertyChanged("HinhAnhTKUV");
					this.OnHinhAnhTKUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai_TKUV", DbType="VarChar(10)")]
		public string SoDienThoai_TKUV
		{
			get
			{
				return this._SoDienThoai_TKUV;
			}
			set
			{
				if ((this._SoDienThoai_TKUV != value))
				{
					this.OnSoDienThoai_TKUVChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai_TKUV = value;
					this.SendPropertyChanged("SoDienThoai_TKUV");
					this.OnSoDienThoai_TKUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="VarChar(50)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_UV_TTD", Storage="_UV_TTDs", ThisKey="Id_UV", OtherKey="Id_UV")]
		public EntitySet<UV_TTD> UV_TTDs
		{
			get
			{
				return this._UV_TTDs;
			}
			set
			{
				this._UV_TTDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_GopY", Storage="_Gopies", ThisKey="Id_UV", OtherKey="Id_UV")]
		public EntitySet<GopY> Gopies
		{
			get
			{
				return this._Gopies;
			}
			set
			{
				this._Gopies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_HoSoXinViec", Storage="_HoSoXinViecs", ThisKey="Id_UV", OtherKey="Id_UV")]
		public EntitySet<HoSoXinViec> HoSoXinViecs
		{
			get
			{
				return this._HoSoXinViecs;
			}
			set
			{
				this._HoSoXinViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_UngVien", Storage="_TaiKhoan", ThisKey="TenTK", OtherKey="TenTK", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.UngViens.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.UngViens.Add(this);
						this._TenTK = value.TenTK;
					}
					else
					{
						this._TenTK = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = this;
		}
		
		private void detach_UV_TTDs(UV_TTD entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = null;
		}
		
		private void attach_Gopies(GopY entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = this;
		}
		
		private void detach_Gopies(GopY entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = null;
		}
		
		private void attach_HoSoXinViecs(HoSoXinViec entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = this;
		}
		
		private void detach_HoSoXinViecs(HoSoXinViec entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = null;
		}
	}
}
#pragma warning restore 1591
